### ISSUE TITLE
Broken AfterFunction brace wrapping

### ISSUE THREAD

**Issue by Sookhaal** [Hazelight/vscode-unreal-angelscript-formatter#5]
Hello!

Using clang-format v20.1.2 (should be irrelevant to the bug).
Here is a quick copy/paste repro:

## Sample repro

Using this config:
```yaml
BraceWrapping:
  AfterFunction: true
BreakBeforeBraces: Custom
ColumnLimit: 0
```

```angelscript
UCLASS()
class ASomeActor : AActor {
  UFUNCTION(BlueprintOverride)
  void BeginPlay() { // <---
  }
}
```

## Expected output

```angelscript
UCLASS()
class ASomeActor : AActor {
  UFUNCTION(BlueprintOverride)
  void BeginPlay()
  { // <---
  }
}
```

## Problem

Nothing happens to the brace. The code breaks right here: https://github.com/Hazelight/vscode-unreal-angelscript-formatter/blob/5cd3eaffc7390c55df05df76acd853c634acc642/src/formatter.ts#L65-L71

Thank you, hope you have a great day!
