### ISSUE TITLE
`private` access specifier will not be indented as a function

### ISSUE THREAD

**Issue by DaqiHu** [Hazelight/vscode-unreal-angelscript-formatter#6]
Here's a simple test:

```cpp
class ATestActor : AActor
{
    UPROPERTY(DefaultComponent, RootComponent)
    USceneComponent Root;

private AActor MyActor;

    UFUNCTION()
private void HandleTimer()
    {
    }

    UFUNCTION(BlueprintOverride)
    void BeginPlay()
    {
        System::SetTimer(this, n"HandleTimer", 1.0f, false);
    }
};
```

These are how the `private` variables and functions look like after being formatted. It's obvious that these two private statements should be indented.

My versions (all of them are latest):

- this plugin: 1.0.0
- LLVM: 20.1.2
- clang-format: 20.1.2
- VSCode (Cursor): 1.96.2

My `.clang-format`:

```yaml
---
Language: Cpp
BasedOnStyle: LLVM
AccessModifierOffset: -4
AlignAfterOpenBracket: BlockIndent
AlignConsecutiveAssignments: true
AlignConsecutiveDeclarations: false
AlignOperands: AlignAfterOperator
BreakBeforeBinaryOperators: NonAssignment
AlignTrailingComments: true
AlwaysBreakTemplateDeclarations: Yes
AllowShortBlocksOnASingleLine: Never
AllowShortFunctionsOnASingleLine: None
AllowShortCaseLabelsOnASingleLine: true
BraceWrapping: 
  AfterCaseLabel: true
  AfterClass: true
  AfterControlStatement: true
  AfterEnum: true
  AfterFunction: true
  AfterNamespace: true
  AfterStruct: true
  AfterUnion: true
  AfterExternBlock: false
  BeforeCatch: true
  BeforeElse: true
  BeforeLambdaBody: true
  BeforeWhile: true
  SplitEmptyFunction: true
  SplitEmptyRecord: true
  SplitEmptyNamespace: true
BreakBeforeBraces: Custom
BreakConstructorInitializers: AfterColon
BreakConstructorInitializersBeforeComma: false
ContinuationIndentWidth: 4
ColumnLimit: 160
ConstructorInitializerAllOnOneLineOrOnePerLine: false
IncludeCategories: 
  - Regex: '^<.*'
    Priority: 1
  - Regex: '^".*'
    Priority: 2
  - Regex: '.*'
    Priority: 3
IncludeIsMainRegex: '([-_](test|unittest))?$'
IndentCaseBlocks: true
IndentWidth: 4
InsertNewlineAtEOF: true
MacroBlockBegin: ''
MacroBlockEnd: ''
MaxEmptyLinesToKeep: 1
NamespaceIndentation: All
SpaceInEmptyParentheses: false
SpacesInAngles: false
SpacesInConditionalStatement: false
SpacesInCStyleCastParentheses: false
SpacesInParentheses: false
TabWidth: 4
PointerAlignment: Left
ReferenceAlignment: Left
SortIncludes: Never
...
```
